### ISSUE TITLE
azure storage error API crashes in http request deep Copy()

### ISSUE THREAD

**Issue by harshavardhana** [Azure/azure-storage-blob-go#304]
https://github.com/Azure/azure-storage-blob-go/blob/4604c9fd081b9a42386443b49aed0b1bf28a51de/azblob/zc_storage_error.go#L74

This line crashes when looking up a non-existent key

```
2021/08/26 23:18:52 http: panic serving 172.17.0.1:65194: Can't make a deep copy of the http.Request because at least one of the following is not nil:TransferEncoding, Form, PostForm, MultipartForm, or Trailer.
goroutine 544 [running]:
net/http.(*conn).serve.func1(0xc00053e000)
	net/http/server.go:1804 +0x153
panic(0x2e2fb40, 0x44d96e0)
	runtime/panic.go:971 +0x499
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0xc0006def00, 0x456b2a0, 0xc0015801c0)
	github.com/minio/minio/cmd/generic-handlers.go:532 +0x1ac
panic(0x2e2fb40, 0x44d96e0)
	runtime/panic.go:965 +0x1b9
github.com/Azure/azure-pipeline-go/pipeline.Request.Copy(0xc0001ff500, 0x33c97c1)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/request.go:79 +0x415
github.com/Azure/azure-storage-blob-go/azblob.(*storageError).Error(0xc0006fc5a0, 0xc000644480, 0xc000466b88)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:74 +0x505
github.com/Azure/azure-pipeline-go/pipeline.WriteRequestWithResponse(0xc000644480, 0xc0001ff400, 0xc001386360, 0x45134c0, 0xc0006fc5a0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/response.go:50 +0x1e2
github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1(0x4577b28, 0xc001465aa0, 0xc0001ff400, 0x10, 0x2e4a340, 0x1, 0xc00067a420)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_request_log.go:94 +0x508
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00106ae10, 0x4577b28, 0xc001465aa0, 0xc0001ff400, 0xc00067a508, 0xc000678280, 0x42, 0xc0007c68a0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.(*SharedKeyCredential).New.func1(0x4577b28, 0xc001465aa0, 0xc0001ff400, 0x5c21680, 0x4577b28, 0xc001465aa0, 0xc000e2f0a0)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_credential_shared_key.go:66 +0x2f4
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000afdbc0, 0x4577b28, 0xc001465aa0, 0xc0001ff400, 0xc001465aa0, 0xc000e2f0a0, 0x1, 0x0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewRetryPolicyFactory.func1.1(0x4577b60, 0xc000afd8f0, 0xc0001ff300, 0x10, 0x2e4a340, 0x64492d747301, 0xc0003b5e40)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_retry.go:204 +0x69d
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc00106ae60, 0x4577b60, 0xc000afd8f0, 0xc0001ff300, 0xc0003b5ef8, 0x40db9b, 0xc000e2efc0, 0x10)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x4577b60, 0xc000afd8f0, 0xc0001ff300, 0x10, 0x2e4a340, 0x40e201, 0xc0003b5e40)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_unique_request_id.go:19 +0xae
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000ed8990, 0x4577b60, 0xc000afd8f0, 0xc0001ff300, 0xc0003b5ee0, 0x24, 0xc00078c8a0, 0xc000467330)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x4577b60, 0xc000afd8f0, 0xc0001ff300, 0x1, 0x0, 0x1, 0xc000c96148)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_policy_telemetry.go:34 +0x162
github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc000afdc20, 0x4577b60, 0xc000afd8f0, 0xc0001ff300, 0xc000afdc20, 0x0, 0xc000467400, 0x40e2f8)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:43 +0x44
github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0005198c0, 0x4577b60, 0xc000afd8f0, 0x451b7a0, 0xc0006e6a50, 0xc0001ff300, 0x21, 0xc0007c67b0, 0x2a, 0x0)
	github.com/Azure/azure-pipeline-go@v0.2.2/pipeline/core.go:129 +0x82
github.com/Azure/azure-storage-blob-go/azblob.blobClient.GetProperties(0xc00078c7e0, 0x5, 0x0, 0x0, 0x0, 0xc00078c7e8, 0x21, 0xc0007c67b0, 0x2a, 0x0, ...)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zz_generated_blob.go:888 +0x3c5
github.com/Azure/azure-storage-blob-go/azblob.BlobURL.GetProperties(0xc00078c7e0, 0x5, 0x0, 0x0, 0x0, 0xc00078c7e8, 0x21, 0xc0007c67b0, 0x2a, 0x0, ...)
	github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/url_blob.go:118 +0x132
```

**Comment by vadmeste** [comment]
Taking this. I will try to find a workaround.
